---
extends:
  # see node_modules/@wordpress/eslint-plugin/README.md
  - plugin:@wordpress/eslint-plugin/recommended
  - plugin:prettier/recommended
  - prettier

# tells ESLint not to use ancestor directories.
# see https://github.com/eslint/eslint/issues/6630
root: true

env:
  es6: true
  browser: true
  jquery: true

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  requireConfigFile: false

plugins:
  - jsx
  - prettier

# we need to override the prettier/prettier rule since
# plugin:@wordpress/eslint-plugin/recommended configures prettier to use tabs instead of spaces
# unfortunely @wordpress/eslint-plugin also ignore prettier setting made in our package.json
# so we need to fix this here as last option ...
rules:
  prettier/prettier:
    - error
    - useTabs: false
  # added to workaround notices after upgrading wp repo (lars)
  import/no-unresolved:
    - off
  '@wordpress/no-global-event-listener':
    - off
  '@wordpress/no-global-active-element':
    - off
